spring.application.name=ShopBilling Manager
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop_billing_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
logging.level.com.shopbilling=INFO
logging.level.org.springframework.security=WARN

app.shop.name=Shiv Shakti Krishi Sewa Kendra
app.shop.address=Betul
app.shop.gst=
